<%@ Page Language="C#" AutoEventWireup="true" CodeFile="CelendarFromADatabase.aspx.cs" Inherits="CelendarFromADatabase" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Rendering a Calendar from a Database Table</title>
    <style type="text/css">
        .auto-style1 {
            width: 409px;
        }
    </style>
</head>
<body bgcolor ="#CCCCFF">
    <form id="form1" runat="server">
        <br />
        <asp:Label ID="Label1" runat="server" Font-Bold="True" Font-Size="X-Large" ForeColor="#000099" Text="Đề mô Rendering a Calendar from a Database Table."></asp:Label>
        <br />
        <br />
        <table style="width: 100%;">
            <tr>
                <td>
                    <asp:Label ID="Label3" runat="server" Text="Mã nhân viên"></asp:Label>
                </td>
                <td class="auto-style1">
                    <asp:TextBox ID="txtMa" runat="server" Width="214px"></asp:TextBox>
                </td>
                <td rowspan="5">
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataKeyNames="MaNV" DataSourceID="SqlDataSource1" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" ForeColor="#333333" GridLines="None">
            <AlternatingRowStyle BackColor="White" />
            <Columns>
                <asp:BoundField DataField="MaNV" HeaderText="Mã nhân viên" ReadOnly="True" SortExpression="MaNV" />
                <asp:BoundField DataField="HoNV" HeaderText="Họ " SortExpression="HoNV" />
                <asp:BoundField DataField="TenNV" HeaderText="Tên" SortExpression="TenNV" />
                <asp:BoundField DataField="NgaySinh" HeaderText="Ngày Sinh" ReadOnly="True" SortExpression="NgaySinh" />
            </Columns>
            <EditRowStyle BackColor="#2461BF" />
            <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
            <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
            <RowStyle BackColor="#EFF3FB" />
            <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
            <SortedAscendingCellStyle BackColor="#F5F7FB" />
            <SortedAscendingHeaderStyle BackColor="#6D95E1" />
            <SortedDescendingCellStyle BackColor="#E9EBEF" />
            <SortedDescendingHeaderStyle BackColor="#4870BE" />
        </asp:GridView>
                </td>
            </tr>
            <tr>
                <td>
                    <asp:Label ID="Label4" runat="server" Text="Họ"></asp:Label>
                </td>
                <td class="auto-style1">
                    <asp:TextBox ID="txtHo" runat="server" Width="213px"></asp:TextBox>
                </td>
            </tr>
            <tr>
                <td>
                    <asp:Label ID="Label5" runat="server" Text="Tên"></asp:Label>
                </td>
                <td class="auto-style1">
                    <asp:TextBox ID="txtTen" runat="server" Width="213px"></asp:TextBox>
                </td>
            </tr>
            <tr>
                <td>Ngày Sinh</td>
                <td class="auto-style1">
                    <asp:TextBox ID="txtNgaySinh" runat="server" Width="213px"></asp:TextBox>
&nbsp;<asp:ImageButton ID="ibtnCelendar" runat="server" Height="20px" ImageUrl="~/Image/DICH-VU-IN-HINH-LEN-LICH-DE-BAN_2013102213553903.jpg" Width="62px" OnClick="ibtnCelendar_Click" />
                    <asp:Calendar ID="Calendar1" runat="server" BackColor="#FFFFCC" BorderColor="#FFCC66" BorderWidth="1px" DayNameFormat="Shortest" Font-Names="Verdana" Font-Size="8pt" ForeColor="#663399" Height="200px" OnSelectionChanged="Calendar1_SelectionChanged" ShowGridLines="True" Width="220px">
                        <DayHeaderStyle BackColor="#FFCC66" Font-Bold="True" Height="1px" />
                        <NextPrevStyle Font-Size="9pt" ForeColor="#FFFFCC" />
                        <OtherMonthDayStyle ForeColor="#CC9966" />
                        <SelectedDayStyle BackColor="#CCCCFF" Font-Bold="True" />
                        <SelectorStyle BackColor="#FFCC66" />
                        <TitleStyle BackColor="#990000" Font-Bold="True" Font-Size="9pt" ForeColor="#FFFFCC" />
                        <TodayDayStyle BackColor="#FFCC66" ForeColor="White" />
                    </asp:Calendar>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <asp:Label ID="Label7" runat="server" Font-Bold="True" Font-Size="Large" ForeColor="#000099"></asp:Label>
                </td>
            </tr>
        </table>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <asp:Button ID="btnInsert" runat="server" Text="Insert" OnClick="btnInsert_Click" />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <asp:Button ID="btnCancel" runat="server" Text="Cancel" OnClick="btnCancel_Click" />
        <br />
        <asp:Label ID="Label6" runat="server" Font-Bold="True" Font-Size="X-Large" ForeColor="#FF3300"></asp:Label>
        <br />
        <br />
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" SelectCommand="SELECT MaNV, HoNV, TenNV, CONVERT(nvarchar(50), NgaySinh, 103 ) as NgaySinh FROM NhanVien ORDER BY TenNV" DeleteCommand="DELETE NhanVien WHERE MaNV = @MaNV" UpdateCommand="UPDATE NhanVien SET HoNV = @HoNV, TenNV = @TenNV WHERE MaNV = @MaNV">
            <DeleteParameters>
                <asp:Parameter Name="MaNV" />
            </DeleteParameters>
            <UpdateParameters>
                <asp:ControlParameter ControlID="GridView1" Name="HoNV" PropertyName="SelectedValue" />
                <asp:ControlParameter ControlID="GridView1" Name="TenNV" PropertyName="SelectedValue" />
                <asp:ControlParameter ControlID="GridView1" Name="MaNV" PropertyName="SelectedValue" />
            </UpdateParameters>
        </asp:SqlDataSource>
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
    </form>
</body>
</html>
